const menuBtn=document.getElementById('menuBtn');
const mobileMenu=document.getElementById('mobileMenu');
if(menuBtn) menuBtn.onclick=()=>mobileMenu.classList.toggle('hidden');
mobileMenu.querySelectorAll('a').forEach(a=>a.onclick=()=>mobileMenu.classList.add('hidden'));

const SITE_ORIGIN=window.location.origin;
const GOOGLE_SCRIPT_URL='https://script.google.com/macros/s/AKfycbzXqgFn1BZv4vcuetNv9J7vF0bmU-PhJ9QIiG2ayVSsVqFZRExrs1IM5tRM13mFXGtu/exec';
const CAMPAIGN_IMAGE=SITE_ORIGIN+'/gallery/Campaign%20Sticker.jpeg';
function shareLink(){return SITE_ORIGIN;}
function newsLink(){return SITE_ORIGIN+'/news.html';}

const TASKS=[
{title:'Share Peter Obi Port Harcourt Town Hall (Trending)',desc:'Sunday task: Watch and share the viral NDC town hall from Port Harcourt — Obi & Kwankwaso. Post the full video or the votes-must-count / I am equally ready to die clip in at least two WhatsApp groups and on your status.',share:()=>`Trending NDC video: Peter Obi & Senator Kwankwaso town hall in Port Harcourt.\nOur votes MUST count. A New Nigeria is possible.\nFull town hall: https://youtu.be/-zXVE1fG0nM\nShort clip (Channels): https://youtu.be/ysSFO0qDlkg\nMore videos & news: ${newsLink()}\nOK is Okay | NDC is Okay\nOluwadara Kehinde (Akan) — Yewa North/Imeko-Afon 2027.\n#OKisOkay #NDC2027 #Obidient`},
{title:"Amplify Today's NDC News",desc:'Open the News page, pick a recent story, and share the link with five people.',share:()=>`Trending on NDC: stay informed and share.\nRead & watch: ${newsLink()}\nStand with competent leadership locally — Oluwadara Kehinde (Akan) for Yewa North/Imeko-Afon.\n#OKisOkay #NDC2027`},
{title:'Status: Votes Must Count',desc:'Post a 24-hour WhatsApp/Facebook status: votes must count + OK is Okay + NDC is Okay.',share:()=>`Our votes MUST count in 2027.\nPeter Obi / Kwankwaso — NDC.\nOluwadara Kehinde (Akan) — Yewa North/Imeko-Afon House of Reps.\nOK is Okay | NDC is Okay | Nigeria will be Okay.\n${shareLink()}\n#OKisOkay #NDC2027`},
{title:'WhatsApp Status Drive',desc:"Post today’s campaign message on your WhatsApp status for 24 hours.",share:()=>`OK is Okay! \nOluwadara Kehinde (Akan) for Yewa North/Imeko-Afon 2027.\nTransparent. Tech-driven. Homegrown.\n#OKisOkay #NDC2027\n${shareLink()}`},
{title:'Share in 2 WhatsApp Groups',desc:'Send a respectful campaign update to two community or family groups.',share:()=>`Good day family\nPlease support Oluwadara Kehinde (Akan) — NDC candidate for Yewa North/Imeko-Afon in 2027.\n#OKisOkay\n${shareLink()}`},
{title:'Facebook / Instagram Post',desc:'Post a photo or short write-up about why you support OK.',share:()=>`I stand with Oluwadara Kehinde (Akan) for House of Reps — Yewa North/Imeko-Afon 2027.\nOK is Okay! #OKisOkay #NDC2027\n${shareLink()}`},
{title:'Facebook Reel or Short',desc:'Record 15–30 seconds saying why OK is Okay and post as a Reel.',share:()=>`Oluwadara Kehinde (Akan) is the competent, homegrown choice for Yewa North/Imeko-Afon. OK is Okay!\n${shareLink()}`},
{title:'Post an Engagement Photo',desc:'Share a campaign or community photo with a supportive caption.',share:()=>`From the grassroots Supporting Oluwadara Kehinde (Akan). #OKisOkay\n${shareLink()}`},
{title:'Engage Campaign Posts',desc:'Like and leave a meaningful comment on the latest campaign posts.',share:()=>`Commented in support of Oluwadara Kehinde (Akan) today. #OKisOkay`},
{title:'WhatsApp Broadcast',desc:'Send today’s update to your broadcast list.',share:()=>`Oluwadara Kehinde (Akan) is running under NDC for Yewa North/Imeko-Afon 2027.\nOK is Okay!\n${shareLink()}`},
{title:'Market / Workplace Chat',desc:'Talk briefly about the campaign with someone at the market or work.',share:()=>`Had a good conversation about OK today. Homegrown leadership for Yewa North/Imeko-Afon. #OKisOkay`},
{title:'Share a Campaign Pledge',desc:'Repost one pledge: youth, agriculture, education or accountable representation.',share:()=>`Pledge I support: people-centred representation and youth opportunity for Yewa North/Imeko-Afon.\nOluwadara Kehinde (Akan) 2027. #OKisOkay\n${shareLink()}`},
{title:'Tag 5 Friends',desc:'Tag five people from the constituency on a campaign post.',share:()=>`Tagging friends who care about Yewa North & Imeko-Afon — check Oluwadara Kehinde (Akan) for 2027. #OKisOkay\n${shareLink()}`},
{title:'Profile Frame / Badge',desc:'Add an OK or NDC frame/badge to your profile picture for the week.',share:()=>`Profile updated for the movement. OK is Okay! Oluwadara Kehinde (Akan) — Yewa North/Imeko-Afon 2027.`},
{title:'Youth Voter Reminder',desc:'Remind three young people to check their PVC / registration.',share:()=>`Young people of Yewa North & Imeko-Afon: confirm your PVC. Support competent leadership — OK is Okay!\n${shareLink()}`}
];
function dayOfYear(d){const start=new Date(d.getFullYear(),0,0);return Math.floor((d-start)/86400000);}
function pickDailyTask(){
  const today=new Date();
  const iso=today.toISOString().slice(0,10);
  const featured={'2026-09-04':0,'2026-09-05':1,'2026-09-06':0,'2026-09-07':1,'2026-09-08':2};
  if(featured[iso]!=null) return TASKS[featured[iso]%TASKS.length];
  return TASKS[dayOfYear(today)%TASKS.length];
}
let shareBody='';
let sharedOrCopied=false;
const daily=pickDailyTask();
document.getElementById('taskTitle').textContent=daily.title;
document.getElementById('taskDesc').textContent=daily.desc;
shareBody=typeof daily.share==='function'?daily.share():String(daily.share||'');
document.getElementById('shareText').textContent=shareBody;
document.getElementById('taskValue').value=daily.title;
document.getElementById('dateLabel').textContent=new Date().toLocaleDateString('en-NG',{weekday:'long',year:'numeric',month:'long',day:'numeric'});
function unlockLog(){sharedOrCopied=true;document.getElementById('doThisBtn').classList.remove('hidden');document.getElementById('logHint').classList.add('hidden');}
document.getElementById('copyBtn').onclick=async()=>{try{await navigator.clipboard.writeText(shareBody);}catch(e){const ta=document.createElement('textarea');ta.value=shareBody;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();}document.getElementById('copied').classList.remove('hidden');setTimeout(()=>document.getElementById('copied').classList.add('hidden'),2000);unlockLog();};
document.getElementById('shareBtn').onclick=async()=>{const data={title:'OK is Okay — Oluwadara Kehinde',text:shareBody,url:shareLink()};try{if(navigator.share){if(navigator.canShare){try{const res=await fetch(CAMPAIGN_IMAGE,{mode:'cors'});const blob=await res.blob();const file=new File([blob],'OK-Campaign-Sticker.jpeg',{type:blob.type||'image/jpeg'});const withFile={...data,files:[file]};if(navigator.canShare(withFile)){await navigator.share(withFile);unlockLog();return;}}catch(_){}}await navigator.share(data);unlockLog();return;}}catch(err){if(err&&err.name==='AbortError') return;}try{await navigator.clipboard.writeText(shareBody+'\n'+shareLink());}catch(_){}alert('Share menu not available on this device. Text copied — paste into WhatsApp or any app.');unlockLog();};
document.getElementById('doThisBtn').onclick=()=>{if(!sharedOrCopied) return;document.getElementById('logSection').classList.remove('hidden');document.getElementById('logSection').scrollIntoView({behavior:'smooth'});};
let supporters=[];
function normPhone(p){return String(p||'').replace(/\D/g,'');}
async function loadSupporters(){try{const res=await fetch(GOOGLE_SCRIPT_URL+'?action=supporters&_='+Date.now());const data=await res.json();if(data&&Array.isArray(data.supporters)) supporters=data.supporters;}catch(e){}try{const list=JSON.parse(localStorage.getItem('ok_acts')||'[]');list.forEach(a=>{if(!a.fullName&&!a.phone) return;const ph=normPhone(a.phone);const exists=ph?supporters.some(s=>normPhone(s.phone)===ph):supporters.some(s=>s.name.toLowerCase()===(a.fullName||'').toLowerCase());if(!exists) supporters.push({name:a.fullName||'Supporter',phone:a.phone||''});});}catch(e){}try{const last=JSON.parse(localStorage.getItem('ok_last_volunteer')||'null');if(last&&(last.fullName||last.phone)){const ph=normPhone(last.phone);if(!ph||!supporters.some(s=>normPhone(s.phone)===ph)){supporters.push({name:last.fullName||'You',phone:last.phone||''});}}}catch(e){}supporters.sort((a,b)=>String(a.name||'').localeCompare(String(b.name||'')));}
loadSupporters();
function filterSupporters(q){q=String(q||'').trim().toLowerCase();const digits=q.replace(/\D/g,'');if(!q) return supporters.slice(0,40);return supporters.filter(s=>{const name=(s.name||'').toLowerCase();const phone=normPhone(s.phone);if(name.includes(q)) return true;if(digits.length>=3&&phone.includes(digits)) return true;return false;}).slice(0,40);}
function renderDropdown(list){const box=document.getElementById('nameDropdown');if(!list.length){box.classList.add('hidden');box.innerHTML='';return;}box.innerHTML=list.map((s,i)=>'<button type="button" data-i="'+i+'" class="supporter-item w-full text-left px-4 py-2.5 border-b border-slate-100 text-sm"><span class="font-semibold text-navy">'+(s.name||'Supporter')+'</span><span class="block text-xs text-slate-500">'+(s.phone||'')+'</span></button>').join('');box.classList.remove('hidden');const items=list;box.querySelectorAll('button').forEach(btn=>{btn.onclick=()=>selectSupporter(items[+btn.dataset.i]);});}
function selectSupporter(s){document.getElementById('nameSearch').value=s.name||s.phone||'';document.getElementById('selectedName').value=s.name||'';document.getElementById('selectedPhone').value=s.phone||'';document.getElementById('phoneShown').value=s.phone||'';document.getElementById('phoneDisplay').classList.remove('hidden');document.getElementById('nameDropdown').classList.add('hidden');document.getElementById('strangerBox').classList.add('hidden');document.getElementById('actSubmit').disabled=false;}
const nameSearch=document.getElementById('nameSearch');
nameSearch.addEventListener('focus',()=>renderDropdown(filterSupporters(nameSearch.value)));
nameSearch.addEventListener('input',()=>{document.getElementById('selectedName').value='';document.getElementById('selectedPhone').value='';document.getElementById('phoneDisplay').classList.add('hidden');document.getElementById('actSubmit').disabled=true;const q=nameSearch.value.trim();const list=filterSupporters(q);if(q&&!list.length){document.getElementById('strangerBox').classList.remove('hidden');document.getElementById('nameDropdown').classList.add('hidden');}else{document.getElementById('strangerBox').classList.add('hidden');renderDropdown(list);}});
document.addEventListener('click',(e)=>{if(!e.target.closest('#nameSearch')&&!e.target.closest('#nameDropdown')){document.getElementById('nameDropdown').classList.add('hidden');}});
document.getElementById('activityForm').onsubmit=async(e)=>{e.preventDefault();const fullName=document.getElementById('selectedName').value.trim()||nameSearch.value.trim();const phone=document.getElementById('selectedPhone').value.trim();if(!fullName&&!phone){document.getElementById('actMsg').textContent='Select your name or phone from the list.';document.getElementById('actMsg').className='text-center text-sm text-red-600';document.getElementById('actMsg').classList.remove('hidden');return;}if(!sharedOrCopied){document.getElementById('actMsg').textContent='Please copy or share the task first.';document.getElementById('actMsg').className='text-center text-sm text-red-600';document.getElementById('actMsg').classList.remove('hidden');return;}const payload={type:'activity',fullName,phone,task:document.getElementById('taskValue').value,note:document.getElementById('actNote').value.trim(),timestamp:new Date().toISOString()};document.getElementById('actSubmit').disabled=true;try{await fetch(GOOGLE_SCRIPT_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const local=JSON.parse(localStorage.getItem('ok_acts')||'[]');local.unshift({...payload,at:new Date().toLocaleString('en-NG')});localStorage.setItem('ok_acts',JSON.stringify(local.slice(0,30)));document.getElementById('actMsg').textContent='Activity logged. Thank you!';document.getElementById('actMsg').className='text-center text-sm text-green-600 font-medium';document.getElementById('actMsg').classList.remove('hidden');renderLocalActs();loadLeaderboard();}catch(err){document.getElementById('actMsg').textContent='Could not reach server. Saved on this device.';document.getElementById('actMsg').className='text-center text-sm text-amber-600';document.getElementById('actMsg').classList.remove('hidden');const local=JSON.parse(localStorage.getItem('ok_acts')||'[]');local.unshift({...payload,at:new Date().toLocaleString('en-NG')});localStorage.setItem('ok_acts',JSON.stringify(local.slice(0,30)));renderLocalActs();}document.getElementById('actSubmit').disabled=false;};
function renderLocalActs(){const ul=document.getElementById('localActs');try{const list=JSON.parse(localStorage.getItem('ok_acts')||'[]');if(!list.length){ul.innerHTML='<li class="text-slate-400">No logs on this device yet.</li>';return;}ul.innerHTML=list.slice(0,8).map(a=>'<li><span class="font-medium text-navy">'+(a.task||'Task')+'</span> · '+(a.fullName||a.phone||'')+' · <span class="text-slate-400">'+(a.at||'')+'</span></li>').join('');}catch(e){ul.innerHTML='';}}renderLocalActs();
let galItems=[], gIdx=0, gTimer=null;
function goGal(i){if(!galItems.length) return;gIdx=(i+galItems.length)%galItems.length;document.getElementById('galleryTrack').style.transform='translateX(-'+(gIdx*100)+'%)';document.getElementById('galCaption').textContent=galItems[gIdx].caption||galItems[gIdx].file||'';}
function resetGal(){clearInterval(gTimer);gTimer=setInterval(()=>goGal(gIdx+1),5000);}document.getElementById('galNext').onclick=()=>{goGal(gIdx+1);resetGal();};document.getElementById('galPrev').onclick=()=>{goGal(gIdx-1);resetGal();};
async function loadGallery(){const track=document.getElementById('galleryTrack');try{const res=await fetch('/gallery/gallery.json?_='+Date.now());galItems=await res.json();}catch(e){galItems=[];}if(!Array.isArray(galItems)||!galItems.length){track.innerHTML='<div class="min-w-full flex items-center justify-center text-slate-500 p-8">Add photos in gallery/gallery.json</div>';return;}track.innerHTML=galItems.map(g=>{const src='/gallery/'+encodeURIComponent(g.file);const isVid=/\.(mp4|webm)$/i.test(g.file||'');if(isVid) return '<div class="min-w-full h-full relative"><video class="w-full h-full object-cover" src="'+src+'" muted playsinline loop></video></div>';return '<div class="min-w-full h-full relative"><img class="w-full h-full object-cover" src="'+src+'" alt="'+(g.caption||'').replace(/"/g,'')+'" loading="lazy"/></div>';}).join('');goGal(0);resetGal();}loadGallery();
function badgeFor(rank,tasks){if(rank===1)return{label:'Gold Champion',cls:'badge-gold text-white'};if(rank===2)return{label:'Silver Mobilizer',cls:'badge-silver text-white'};if(rank===3)return{label:'Bronze Builder',cls:'badge-bronze text-white'};if(tasks>=10)return{label:'Star Volunteer',cls:'bg-brand-green text-white'};if(tasks>=5)return{label:'Active Supporter',cls:'bg-navy text-white'};return{label:'Contributor',cls:'bg-slate-200 text-slate-700'};}
async function loadLeaderboard(){const box=document.getElementById('leaderboard');let leaders=[],week='';try{const res=await fetch(GOOGLE_SCRIPT_URL+'?action=leaderboard&_='+Date.now());const text=await res.text();let data;try{data=JSON.parse(text);}catch(_){data=null;}if(data&&data.leaders){leaders=data.leaders;week=data.week||'';}}catch(err){}if(!leaders.length){try{const list=JSON.parse(localStorage.getItem('ok_acts')||'[]');const map={};list.forEach(a=>{const k=(a.phone||a.fullName||'you').toLowerCase();if(!map[k])map[k]={name:a.fullName||'You',phone:a.phone||'',count:0};map[k].count++;});leaders=Object.values(map).sort((a,b)=>b.count-a.count).slice(0,15).map((l,i)=>({rank:i+1,name:l.name,phone:l.phone?String(l.phone).slice(0,4)+'***':'',tasks:l.count}));if(leaders.length) document.getElementById('weekLabel').textContent='From this device (server ranking after Apps Script update)';}catch(e){}}else if(week) document.getElementById('weekLabel').textContent='Week '+week+' · Top supporters';if(!leaders.length){box.innerHTML='<p class="text-slate-500 text-sm">No activities logged this week yet. Be the first!</p>';return;}box.innerHTML=leaders.map(l=>{const b=badgeFor(l.rank,l.tasks);return '<div class="flex items-center gap-3 p-3 rounded-xl '+(l.rank<=3?'bg-amber-50 border border-amber-100':'bg-slate-50')+'"><span class="w-9 h-9 flex items-center justify-center rounded-full font-bold text-sm '+(l.rank===1?'bg-amber-400 text-white':l.rank===2?'bg-slate-300':l.rank===3?'bg-amber-700 text-white':'bg-slate-200')+'">'+l.rank+'</span><div class="flex-1 min-w-0"><p class="font-semibold text-navy truncate">'+(l.name||'Supporter')+'</p><p class="text-xs text-slate-500">'+(l.phone||'')+'</p><span class="inline-block mt-1 text-[10px] font-bold px-2 py-0.5 rounded-full '+b.cls+'">'+b.label+'</span></div><div class="text-right"><span class="font-bold text-brand-green text-lg">'+l.tasks+'</span><p class="text-[10px] text-slate-400">tasks</p></div></div>';}).join('');}
loadLeaderboard();
