window.TODAY_TASK={
  date:'2026-10-07',
  title:'International Walk to School Day: 101 days, safe routes, and the townhall line',
  desc:'Wednesday, 7 October is International Walk to School Day, and election morning is 101 days away. Share the card below — Oluwadara Kehinde (Akan) and the NDC mark are on it. Caption: Teachers are the reason we are who we are, from our mothers to our tutors. Oluwadara Kehinde (Akan) celebrates every teacher, and asks that children in Yewa North and Imeko-Afon have a safe walk to school, a classroom that works, and a teacher who is paid and respected. Then forward Peter Obi’s NDC Global Digital Townhall line — no tribe buys bread cheaper, no tribe buys fuel cheaper — and the ask to stay at the polling unit until votes are counted. Attach the Teachers Day gallery photo or one ground photo from Ebute, Ilara, Ayetoro, Imasayi, Sawonjo, Sunwa or the Imeko-Afon team, plus your personal referral link.',
  image:'/assets/walk-to-school-ok-2026-10-07.jpg',
  share:function(){
    var origin=window.location.origin;
    var link=(typeof shareLink==='function')?shareLink():origin;
    return 'International Walk to School Day.\n\nTeachers are the reason we are who we are, starting from our mother to our tutors.\nOluwadara Kehinde (Akan) celebrates all teachers today, and asks for a safe walk to school in every ward of Yewa North and Imeko-Afon.\nShare card: '+origin+'/assets/walk-to-school-ok-2026-10-07.jpg\nTeachers Day photo: '+origin+'/gallery/Teachers%20Day%202026.jpg\n\n101 days to 16 January 2027, 9:00am Nigerian time.\nTomorrow we cross 100 days. Stay ready.\n\nFrom the NDC Global Digital Townhall with Peter Obi:\nNo tribe buys bread cheaper. No tribe buys fuel cheaper. A divided Nigeria needs a unifying leader. Stay at your polling unit until the votes are counted.\nReplay: https://www.youtube.com/watch?v=Fd4LAXWqZUk\nReport: https://authorityngr.com/2026/10/06/2027-put-national-unity-first-but-protect-your-votes-obi-charges-supporters/\n\nOur ground — attach one: Teachers Day, Ebute, Ilara, Ayetoro, Imasayi, Sawonjo & Sunwa, Imeko-Afon team.\nGallery: '+origin+'/tasks.html#gallery\nMore NDC videos: '+origin+'/ndc.html\n\nOK is Okay | NDC is Okay | Nigeria will be Okay\nJoin with my link: '+link+'\n#OKisOkay #NDC2027 #PeterObi #WalkToSchoolDay #101Days #YewaNorth #ImekoAfon';
  }
};
